micronaut:
  application:
    name: fretesRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    fretes:
      address: 'localhost:8082'
      plaintext: true
      max-retry-attempts: 10

